### ISSUE TITLE
Report on xgap-4.30 installation 

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/xgap#12]
Installation on my iMac, running macOS High Sierra 10.13.3, was successful today. 
Don't think I have run xgap on this machine before, and I have no intention of using it regularly. 
The README says "# cd xgap" but this should probably be "# cd xgap-4.30" or perhaps 
"# cd xgap-<version number>"? 
Because I was installing in a non-standard location, the following appeared twice when running 'make':    configure: WARNING: unrecognized options: --with-gaproot

**Comment by fingolfin** [comment]
Thank you for the report!

The build system of this package is... interesting. It should ideally be completely replaced, but honestly, I could not be bothered so far...

**Comment by fingolfin** [comment]
I've addressed both the README and the configure warning now.
