### ISSUE TITLE
XGAP not running in macOS because of X Window issue

### ISSUE THREAD

**Issue by ssahamath** [gap-packages/xgap#14]
Hello,

I have been trying to run XGAP in my MacBook (macOS Catalina 10.15.6). The installation (./cofigure and then make went well). Now when I try to run XGAP from the terminal it shows 

sorry: xgap is a program running under the X Window System, so
you need a graphics display.
you must either set $DISPLAY or use "-display HOST:0.0"
where you replace HOST by the name of your machine.

I also tried LoadPackage("xgap") in GAP, it shows fail. 

Any help will be really appreciated.

**Comment by olexandr-konovalov** [comment]
@ssahamath You can compile XGAP in macOS, but to run it you need to install XQuartz https://www.xquartz.org/ to get an X Window system for macOS. Then when you start it, change to the XGAP directory of your GAP installation, and start it using `bin/xgap.sh` script.

**Comment by RussWoodroofe** [comment]
@ssahamath, if you need to interactively work with subgroup lattice or use most other programs that rely on XGAP on a Mac, you might also be interested in my Gap.app frontend, which is XGAP compatible and may be somewhat easier to install.  https://cocoagap.sourceforge.io/
