### ISSUE TITLE
Doesn't find GAP installation

### ISSUE THREAD

**Issue by yurivict** [gap-packages/xgap#17]
It fails with ```--with-gaproot=/usr/local/share/gap```:
```
********************************************************************
  ERROR

  Found a GAP installation at /usr/local/share/gap but could not find
  information about GAP's architecture in the
  file /usr/local/share/gap/sysinfo.gap or did not find the directory
  /usr/local/share/gap/bin/amd64.
  This file and directory should be present: please check your
  GAP installation.
********************************************************************
```
GAP-4.1.1 doesn't install ```/usr/local/share/gap/bin/amd64```.

**Comment by fingolfin** [comment]
That sounds like a bug in your GAP installation. How was GAP installed?

**Comment by fingolfin** [comment]
Most likely you installed GAP via a package manager and that package manager scrambled GAP in a way that breaks package compiling. Those paths come from GAP's sysinfo.gap file, and if there are invalid ones in there, it's unfortunately something we can't do anything about, the maintainers of the downstream GAP package will need to adjust it. I can try to help them by explaining what needs to be done, if they are interested, but that's the best I can offer ATM.

**Comment by yurivict** [comment]
GAP is installed with the FreeBSD package.

The whole contents of ```/usr/local/share/gap/sysinfo.gap```:
```
# This file has been generated by the GAP build system,
# do not edit manually!
GAParch=amd64
GAP_ABI=64
GAP_HPCGAP=no

GAP_VERSION="4.11.1"
GAP_BUILD_VERSION="4.11.1"
GAP_KERNEL_MAJOR_VERSION=7
GAP_KERNEL_MINOR_VERSION=0

GAP_BIN_DIR="/wrkdirs/usr/ports/math/gap/work/gap-4.11.1"
GAP_LIB_DIR="/wrkdirs/usr/ports/math/gap/work/gap-4.11.1"

GAP_CC="cc "
GAP_CXX="c++ "
GAP_CFLAGS="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "
GAP_CXXFLAGS="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include "
GAP_CPPFLAGS="-I/wrkdirs/usr/ports/math/gap/work/gap-4.11.1/gen -I/wrkdirs/usr/ports/math/gap/work/gap-4.11.1/src -I/wrkdirs/usr/ports/math/gap/work/gap-4.11.1 -DHAVE_CONFIG_H       -I/usr/local/include -isystem /usr/local/include"
GAP_LDFLAGS="      -L/usr/local/lib -fstack-protector-strong "
GAP_LIBS="-lgmp -lz -lreadline    -lexecinfo -lm -lutil -L/usr/local/lib"

GAP_OBJS="obj/src/ariths.lo obj/src/bags.lo obj/src/blister.lo obj/src/bool.lo obj/src/c_oper1.lo obj/src/c_type1.lo obj/src/calls.lo obj/src/code.lo obj/src/collectors.lo obj/src/compiler.lo obj/src/compstat.lo obj/src/costab.lo obj/src/cyclotom.lo obj/src/debug.lo obj/src/dt.lo obj/src/dteval.lo obj/src/error.lo obj/src/exprs.lo obj/src/ffdata.lo obj/src/finfield.lo obj/src/funcs.lo obj/src/gap.lo obj/gen/gap_version.lo obj/src/gvars.lo obj/src/hookintrprtr.lo obj/src/info.lo obj/src/integer.lo obj/src/intfuncs.lo obj/src/intrprtr.lo obj/src/io.lo obj/src/iostream.lo obj/src/libgap-api.lo obj/src/listfunc.lo obj/src/listoper.lo obj/src/lists.lo obj/src/macfloat.lo obj/src/modules.lo obj/src/modules_builtin.lo obj/src/objcftl.lo obj/src/objects.lo obj/src/objfgelm.lo obj/src/objpcgel.lo obj/src/objset.lo obj/src/opers.lo obj/src/permutat.lo obj/src/plist.lo obj/src/pperm.lo obj/src/precord.lo obj/src/profile.lo obj/src/range.lo obj/src/rational.lo obj/src/read.lo obj/src/records.lo obj/src/saveload.lo obj/src/scanner.lo obj/src/sctable.lo obj/src/set.lo obj/src/stats.lo obj/src/streams.lo obj/src/stringobj.lo obj/src/syntaxtree.lo obj/src/sysfiles.lo obj/src/sysmem.lo obj/src/system.lo obj/src/tietze.lo obj/src/trans.lo obj/src/vars.lo obj/src/vec8bit.lo obj/src/vecffe.lo obj/src/vecgf2.lo obj/src/vector.lo obj/src/weakptr.lo obj/src/gasman.lo"

JULIA=""
JULIA_CPPFLAGS=""
JULIA_LDFLAGS=""
JULIA_LIBS=""
```

It does mention architecture: ```GAParch=amd64```.

**Comment by fingolfin** [comment]
Ahhh, I see. OK. I'll see if I can address this as part of PR #18

**Comment by yurivict** [comment]
Additionally, these lines:
```
GAP_BIN_DIR="/wrkdirs/usr/ports/math/gap/work/gap-4.11.1"
GAP_LIB_DIR="/wrkdirs/usr/ports/math/gap/work/gap-4.11.1"
```
were wrong. I just corrected them in the port, so now they read:
```
GAP_BIN_DIR="/usr/local/bin"
GAP_LIB_DIR="/usr/local/lib"
```

**Comment by fingolfin** [comment]
This should be fixed in PR #18, which I just merged. If you have a chance to try it, let me know if it actually does.

**Comment by yurivict** [comment]
Now the build fails:
```
===>  Building for xgap-4.30.15
gmake[1]: Entering directory '/disk-samsung/freebsd-ports/math/xgap/work/xgap-4.30-15-ga8f863e'
gmake[1]: *** No rule to make target 'cnf/configure.out', needed by 'bin/amd64-portbld-freebsd13.0-cc/configure'.  Stop.
gmake[1]: Leaving directory '/disk-samsung/freebsd-ports/math/xgap/work/xgap-4.30-15-ga8f863e'
===> Compilation failed unexpectedly.
```

**Comment by fingolfin** [comment]
Did you run `./autogen.sh` first? (This will be taken care of in release tarballs, but when using the repository directly it has to be invoked manually)

**Comment by fingolfin** [comment]
I just released xgap 4.31, maybe you can test with the release tarball?

**Comment by yurivict** [comment]
Now it builds, but there's no install target:
> gmake[1]: *** No rule to make target 'install'.  Stop.

Also when I run the xgap executable it fails:
> Panic: cannot establish communication with gap.

**Comment by fingolfin** [comment]
GAP packages never have install targets.

The panic is weird. Perhaps it failed to locate or launch GAP. Huh

**Comment by yurivict** [comment]
> The panic is weird. Perhaps it failed to locate or launch GAP. Huh

It should say what exactly happened in more details.

**Comment by RussWoodroofe** [comment]
Are you starting xgap directly, or via the xgap.sh script?  (Try the latter if you weren't already.)

**Comment by yurivict** [comment]
It tries to use a non-existent executable:
```
GAP executable:    /usr/local/share/gap/bin/amd64/gap
```
and fails in this way.

xgap should produce an adequate error message.

**Comment by RussWoodroofe** [comment]
If you fix the path in xgap.sh, or call xgap with correct arguments directly, then does it work?
As far as better error messages: a sensible (and easy) sanity check would be for xgap.sh to check for existence of `$XGAP`, `$GAP`, and/or `$GAP_DIR`, and complain if any of these are missing.

**Comment by yurivict** [comment]
I had to patch xgap.sh with the correct path for it to work.

But the xgap binary itself should produce a better message.  Obviously, it tried to run the gap executable, failed, and lost that error message.

**Comment by fingolfin** [comment]
Well, in a standard setup, `xgap.sh` seems to work fine. So it still seems as if something is fishy with your GAP installation. What exactly did you edit and how?

That said, sure, better checks and error messages are always good. But the reality is: this package is basically abandoned. I volunteered as maintainer because nobody else did, but I don't use it myself, and I'd be happy if someone else took that baton. In any case, I don't really have time to work on this more; I just did some emergency updates, and it seems to work well enough on the various Linux and Mac systems I tested it on. Any further improvements in the foreseeable future will have to come from others, I am afraid. Sorry.

**Comment by yurivict** [comment]
xgap.sh is patched by the FreeBSD port before it is installed.
Otherwise xgap prints an inadequate error.

**Comment by RussWoodroofe** [comment]
I also don't use xgap directly (although I do use its library through Gap.app, and this aspect of it is of quite some interest to me).  But I can try to put together a patch with some sensible error-checking for xgap.sh.  It will take me some time to get to it.  Or, @yurivict , I'm not sure I understand your last message -- does FreeBSD already have some patches for better error messages in xgap.sh?

I don't want to mess with the C program at this time, as I think the chance of introducing a new problem is too high relative to the payoff.

**Comment by fingolfin** [comment]
As far as I can tell, the issue reported here has been fixed. Feel free to open an issue requesting better error messages, but unless a new contributor pops out of nowhere, I am afraid it won't be addressed for the reasons already explained above. :-(
