### ISSUE TITLE
Wrong path in xgap.sh

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/xgap#2]
Tricia Heggie reported the following regression:

```
Installed gap4r8 on scientific Linux 6 in /usr/local.
/usr/local//bin/xgap.sh won’t run giving error:


line 300: /usr/local/gap4r8/pkg/xgap/bin/x86_64-unknown-linux-gnu-gcc/xgap: No such file or directory

The xgap package in /usr/local/gap4r8/pkg/ is now called xgap-4.24 not xgap.
```

To fix this, we simply need to adjust xgap.shi, and insert the version in the right spot. This should be done before the next release.

**Comment by ndrean** [comment]
I found I had to remane the folder "~/pkg/xgap-4.24" into "/pkg/xgap".

**Comment by olexandr-konovalov** [comment]
@fingolfin if you can make a release to be picked up on Friday Nov 4th, it could make it into GAP 4.8.6 distribution.

**Comment by fingolfin** [comment]
@alex-konovalov Not sure if that was still on time, but I couldn't get to it sooner. Anyway, if it's not in 4.8.6, it'll get into 4.8.7 or 4.9.0
