### ISSUE TITLE
problem loading xgap

### ISSUE THREAD

**Issue by salahshoori** [gap-packages/xgap#5]

**Comment by olexandr-konovalov** [comment]
@salahshoori please do not vandalise the issue. Even if you have already figured out how to load XGAP, you could write a short comment about that and close the issue yourself. It will help to XGAP maintainers who will not be surprised to see an empty issue, and also may help to other users (e.g. if you have found instructions unclear, and told us what is unclear, we may explain this better in the documentation). Please also note that you're using 2-years old GAP distribution, while the latest release of XGAP has been made a year ago, so it's advised to upgrade to GAP 4.8.8 (August 2017).
